---
title: "R coding and scripting basics"
#author: "Liming Wang"
#date: "8/21/2017"
output: 
  html_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
This section will cover a brief introduction to R and RStudio, some base R topics, and recommendations for adopting a style guide for R. 

## Lessons
1. [Introduction to R and RStudio](http://swcarpentry.github.io/r-novice-gapminder/01-rstudio-intro/)
1. [Data Structures](http://swcarpentry.github.io/r-novice-gapminder/04-data-structures-part1/index.html)
    - How can I read data in R?
    - What are the basic data types in R?
    - How do I represent categorical information in R?
1. [Exploring Data Frames](http://swcarpentry.github.io/r-novice-gapminder/05-data-structures-part2/index.html)
    - How can I manipulate a data frame?
1. [Subsetting Data](http://swcarpentry.github.io/r-novice-gapminder/06-data-subsetting/index.html)
    - How can I work with subsets of data in R?

## Code Style Guide

In programming as in writing, it is generally a good idea to stick to a consitent coding style. There are two style guides that you can adopt or customize to create your own:

- [Google's R style guide](https://google.github.io/styleguide/Rguide.xml)
- [Hadley Wickham's code style guide](http://adv-r.had.co.nz/Style.html)

## Resources
Additional base R lessons can be found [here](http://swcarpentry.github.io/r-novice-gapminder/), courtesy of Software Carpentry, and cover the following additional topics that will not be covered in Part I of this workshop:

- Control flow
- Vectorization
- Functions
- Writing good software